#!/usr/bin/env python3
"""
Figure 1 generator (revised).  Self-contained SVG, no dependencies.
    python3 make_figure1.py   ->   figure1.svg

Layout is authored in POINTS (1 unit = 1 pt).  The canvas is exactly
6.5 in wide (468 pt), so the SVG renders at true print size and the font
sizes below are real point sizes.

Fonts
-----
Standard text : Computer Modern Sans   (CMU Sans Serif / Latin Modern Sans)
Dataset tags  : Computer Modern Typewriter  (\\texttt)
Math / symbols: Computer Modern Roman italic (\\mathit)
These are referenced by family name; install the TeX "cm-unicode"
(CMU *) or "lm" (Latin Modern) fonts so a viewer picks them up.  Sensible
sans / serif / mono fall-backs are chained after them.

Blanks to fill are the `n=None` and `umis=None` fields in the DATA block;
they render as light underlines.
"""

import math, random, os, sys

OUT_SVG = "analysis/figures/figure1.svg"

# ---- embedded Computer Modern faces (base64 @font-face, WOFF2) -------
# Generated by the sidecar tooling from the CMU-Unicode OTFs so the figure
# renders in genuine Computer Modern in any viewer, with no fonts installed.
HERE = os.path.dirname(os.path.abspath(__file__))
try:
    with open(os.path.join(HERE, "cm_fonts_face.css"), encoding="utf-8") as _fh:
        FONT_CSS = _fh.read()
except OSError:
    FONT_CSS = ""   # falls back to whatever CM fonts the viewer has installed

# ---- physical size -------------------------------------------------
IN   = 72.0                 # pt per inch
W    = 6.5 * IN             # 468 pt canvas width
M    = 15                   # page margin (pt)

# ---- palette (one quiet teal accent; warm only inside noise map) ---
INK    = "#1A2230"
SUB    = "#69747F"
FAINT  = "#AEB7C0"
HAIR   = "#D6DBE1"
HAIR2  = "#EAEDF0"
ACCENT = "#1E6E7A"
ACC_BG = "#EAF2F2"
ARROW  = "#8A96A3"

# ---- Computer Modern font stacks -----------------------------------
SANS = ("'CMU Sans Serif','Latin Modern Sans','Computer Modern Sans Serif',"
        "'Helvetica Neue',Arial,sans-serif")
TT   = ("'CMU Typewriter Text','Latin Modern Mono',"
        "'Computer Modern Typewriter',Menlo,Consolas,monospace")
MATH = ("'CMU Serif','Latin Modern Math','Latin Modern Roman',"
        "'Computer Modern',Georgia,'Times New Roman',serif")

# ---- real CM advance widths (baked from the OTFs) ------------------
# Lets us place/centre/wrap text exactly instead of guessing, so nothing
# ever has to be glyph-stretched to fit.
sys.path.insert(0, HERE)
try:
    from cm_metrics import CM_WIDTHS
except Exception:
    CM_WIDTHS = {}

def _face_key(fam, weight, style):
    if fam is TT:   return "tt"
    if fam is MATH: return "serifi" if style == "italic" else "serif"
    if weight == "bold": return "sansb"
    return "sansi" if style == "italic" else "sans"

def text_width(s, size, fam=SANS, weight="normal", style="normal"):
    """Width of `s` in points, from real Computer Modern metrics."""
    tbl = CM_WIDTHS.get(_face_key(fam, weight, style))
    if not tbl:                                   # fallback if metrics missing
        f = 0.60 if fam is TT else 0.50
        return len(str(s)) * size * f
    d = tbl.get("_def", 0.5)
    return size * sum(tbl.get(ch, d) for ch in str(s))

# ---- type scale (pt) -----------------------------------------------
F_PANEL = 11   # panel letters a / b
F_BODY  = 8    # table body / aux labels
F_HEAD  = 8    # table headers
F_MOD   = 8    # merged modality text
F_MODEL = 8    # merged model list
F_NOI   = 8    # merged noising text
F_CAP   = 8    # captions above matrices
F_TITLE = 8    # aux-panel titles
F_SUB   = 8    # subtitles / assay / annotations
F_TAG   = 8    # \texttt tags
F_SYM   = 10   # math symbols  X, Z, epsilon ...
F_MATH  = 11   # node I(Z;Y)
F_AXIS  = 7    # plot axis labels (compact panel; smallest in the figure)

CMAP = {
    "clean": ("#EAF1F7", "#2F5D86"),
    "noise": ("#F6ECE6", "#C0824F"),
    "noisy": ("#ECE9F3", "#574B87"),
    "rep":   ("#E4EEEF", ACCENT),
}

# =====================================================================
# DATA  --  `tag` must match Fig. 2.  n / umis = None -> fill-in blank.
# =====================================================================
AUX_PANELS = [
    dict(kind="spatial", title="Spatial neighbors", assay="MERFISH",           tag="Spatial"),
    dict(kind="clone",   title="Clonal neighbors",  assay="LARRY",             tag="Clonal"),
    dict(kind="cite",    title="Surface protein",    assay="CITE-seq",          tag="Protein"),
    dict(kind="time",    title="Developmental time", assay="time-series scSeq", tag="Temporal"),
]

GROUPS = [
    dict(
        modality=["Single-cell &", "spatial", "transcriptomics"],
        models=["scVI", "Geneformer", "STATE", "PCA", "Random projection"],
        noise=["Transcript count", "downsampling"],
        rows=[
            dict(tag="Spatial",  aux=["Spatial neighbor", "expression (MERFISH)"],  n=60000,    umis=367),
            dict(tag="Clonal",   aux=["Clonal neighbor", "expression (LARRY)"],     n=100000,   umis=2580),
            dict(tag="Protein",  aux=["Protein abundance", "(CITE-seq)"],           n=100000,   umis=8100),
            dict(tag="Temporal", aux=["Embryo stage"],                              n=10000000, umis=2500),
        ],
    ),
    dict(
        modality=["Images"],
        models=["MobileNetV2"],
        noise=["Pixel-wise additive", "Gaussian;", "pixelation"],
        rows=[
            dict(tag="TissueMNIST", aux=["Kidney cell type", "(fluorescence", "microscopy)"], n=236386, umis="na"),
            dict(tag="Caltech101",  aux=["Image label"],                                      n=2707,   umis="na"),
        ],
    ),
    dict(
        modality=["Protein", "sequences"],
        models=["ESM2"],
        noise=["Amino-acid", "substitution error"],
        rows=[
            dict(tag="Spike", aux=["Collection month", "(SARS-CoV-2 spike)"], n=63374, umis="na"),
        ],
    ),
]

# =====================================================================
# helpers
# =====================================================================
def esc(s):
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def _lerp(c1, c2, t):
    a = [int(c1[i:i+2], 16) for i in (1, 3, 5)]
    b = [int(c2[i:i+2], 16) for i in (1, 3, 5)]
    return "#%02X%02X%02X" % tuple(round(a[i] + (b[i]-a[i])*t) for i in range(3))

def T(x, y, s, size=F_BODY, fam=SANS, fill=INK, weight="normal",
      anchor="start", style="normal", spacing=None, max_w=None, opacity=None):
    """Text.  `max_w` is a safety net only: it condenses on genuine overflow
    (measured with real metrics) and can never stretch a glyph."""
    tl = ""
    if max_w and len(str(s)) > 1:
        natural = text_width(s, size, fam, weight, style)
        if natural > max_w + 0.5:
            tl = f' textLength="{max_w:.1f}" lengthAdjust="spacingAndGlyphs"'
    ls = f' letter-spacing="{spacing}"' if spacing is not None else ""
    op = f' opacity="{opacity}"' if opacity is not None else ""
    return (f'<text x="{x:.2f}" y="{y:.2f}" font-family="{fam}" font-size="{size}" '
            f'font-weight="{weight}" font-style="{style}" fill="{fill}" '
            f'text-anchor="{anchor}"{ls}{op}{tl}>{esc(s)}</text>')

def stack(x, y0, lines, dy, **kw):
    return "".join(T(x, y0 + i*dy, ln, **kw) for i, ln in enumerate(lines))

def line(x1, y1, x2, y2, stroke=HAIR, w=0.5, dash=None, cap="butt", marker=None):
    d = f' stroke-dasharray="{dash}"' if dash else ""
    m = f' marker-end="url(#{marker})"' if marker else ""
    return (f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" '
            f'stroke="{stroke}" stroke-width="{w}" stroke-linecap="{cap}"{d}{m}/>')

def rrect(x, y, w, h, rx=2, fill="none", stroke="none", sw=0.5):
    return (f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" rx="{rx}" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}"/>')

def circle(cx, cy, r, fill="none", stroke=INK, sw=0.6):
    return (f'<circle cx="{cx:.2f}" cy="{cy:.2f}" r="{r:.2f}" fill="{fill}" '
            f'stroke="{stroke}" stroke-width="{sw}"/>')

def path(d, fill="none", stroke=INK, sw=0.6):
    return (f'<path d="{d}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}" '
            f'stroke-linecap="round" stroke-linejoin="round"/>')

def heat(x, y, rows, cols, ramp, seed, cell=4.2, gap=1.0, rx=0.7):
    lo, hi = CMAP[ramp]
    rnd = random.Random(seed)
    out = []
    for r in range(rows):
        for c in range(cols):
            t = 0.10 + 0.85 * (rnd.random() ** 1.15)
            out.append(f'<rect x="{x+c*(cell+gap):.2f}" y="{y+r*(cell+gap):.2f}" '
                       f'width="{cell:.2f}" height="{cell:.2f}" rx="{rx}" '
                       f'fill="{_lerp(lo, hi, t)}"/>')
    return "".join(out), cols*cell+(cols-1)*gap, rows*cell+(rows-1)*gap

def blank(x, y, w=24):
    return line(x, y, x+w, y, stroke=FAINT, w=0.8, cap="round")

def group_scale(inner, cx, cy, s):
    """Scale `inner` by `s` about (cx, cy)."""
    return (f'<g transform="translate({cx:.2f} {cy:.2f}) scale({s}) '
            f'translate({-cx:.2f} {-cy:.2f})">{inner}</g>')

# ---- 1a schematic icons (tiny, drawn around cx,cy) ------------------
def icon_spatial(cx, cy):
    p = [circle(cx, cy, 2.6, fill=ACCENT, stroke=ACCENT)]
    for k in range(6):
        a = math.radians(60*k - 90)
        nx, ny = cx + 10*math.cos(a), cy + 10*math.sin(a)
        p.append(line(cx, cy, nx, ny, stroke=HAIR, w=0.5))
        p.append(circle(nx, ny, 2.1, fill="#fff", stroke=INK, sw=0.55))
    return "".join(p)

def icon_clone(cx, cy):
    top = cy - 11
    p = [line(cx, top, cx, top+3.5, stroke=INK, w=0.55)]
    l1, r1 = cx-7, cx+7
    y1 = top+3.5
    p += [path(f"M{l1},{y1} L{r1},{y1}", stroke=INK, sw=0.55),
          line(l1, y1, l1, y1+3.5, stroke=INK, w=0.55),
          line(r1, y1, r1, y1+3.5, stroke=INK, w=0.55)]
    y2 = y1+3.5
    leaves = []
    for bx in (l1, r1):
        lx, rx = bx-4, bx+4
        p.append(path(f"M{lx},{y2} L{rx},{y2}", stroke=INK, sw=0.55))
        for lf in (lx, rx):
            p.append(line(lf, y2, lf, y2+3.2, stroke=INK, w=0.55))
            leaves.append(lf)
    ly = y2+3.2
    clone = {leaves[1], leaves[2]}
    for lf in leaves:
        if lf in clone:
            p.append(circle(lf, ly+2, 2.1, fill=ACCENT, stroke=ACCENT))
        else:
            p.append(circle(lf, ly+2, 2.1, fill="#fff", stroke=INK, sw=0.55))
    return "".join(p)

def icon_cite(cx, cy):
    p = [circle(cx, cy, 7, fill="#fff", stroke=INK, sw=0.7)]
    for k in range(4):
        a = math.radians(45 + 90*k)
        bx, by = cx+7*math.cos(a), cy+7*math.sin(a)
        tx, ty = cx+11*math.cos(a), cy+11*math.sin(a)
        p.append(line(bx, by, tx, ty, stroke=ACCENT, w=0.7))
        perp = a + math.pi/2
        fx, fy = 1.9*math.cos(perp), 1.9*math.sin(perp)
        ex, ey = 1.9*math.cos(a), 1.9*math.sin(a)
        p.append(line(tx, ty, tx+ex+fx, ty+ey+fy, stroke=ACCENT, w=0.7))
        p.append(line(tx, ty, tx+ex-fx, ty+ey-fy, stroke=ACCENT, w=0.7))
    p.append(path(f"M{cx-3.4},{cy+1.8} q1.8,-3.6 3.4,-1 q1.5,2.8 3.4,-0.6",
                  stroke=INK, sw=0.6))
    return "".join(p)

def icon_time(cx, cy):
    """Cleavage stages 1 -> 2 -> 4 cells: constant cell size, growing cluster."""
    yc = cy - 2                      # embryo centre line
    r, d = 2.2, 2.5                  # constant cell radius; half-spacing
    xs = (cx-12, cx-1, cx+11)        # three stage centres
    def cell(x, y):
        return circle(x, y, r, fill=ACC_BG, stroke=ACCENT, sw=0.7)
    p = [cell(xs[0], yc)]                                   # 1-cell
    p += [cell(xs[1]-d, yc), cell(xs[1]+d, yc)]            # 2-cell
    for ddx in (-d, d):                                    # 4-cell (2x2)
        for ddy in (-d, d):
            p.append(cell(xs[2]+ddx, yc+ddy))
    p.append(line(cx-16, cy+8, cx+17, cy+8, stroke=INK, w=0.55, marker="arrowGrey"))
    return "".join(p)

ICON = {"spatial": icon_spatial, "clone": icon_clone,
        "cite": icon_cite, "time": icon_time}

# =====================================================================
S = []
def add(*p): S.extend(p)

DEFS = f'''<defs>
  <style type="text/css">{FONT_CSS}</style>
  <marker id="arrowGrey" markerWidth="5" markerHeight="5" refX="3.6" refY="1.8"
          orient="auto" markerUnits="userSpaceOnUse">
    <path d="M0,0 L4,1.8 L0,3.6 Z" fill="{ARROW}"/></marker>
  <marker id="arrowTeal" markerWidth="5" markerHeight="5" refX="3.6" refY="1.8"
          orient="auto" markerUnits="userSpaceOnUse">
    <path d="M0,0 L4,1.8 L0,3.6 Z" fill="{ACCENT}"/></marker>
</defs>'''

# =====================================================================
# PANEL a
# =====================================================================
add(T(M, 14, "a", size=F_PANEL, weight="bold"))

cy = 58
CAP_Y, SYM_Y = cy-24, cy+25

def cap(cx, s):
    lines = s if isinstance(s, list) else [s]      # bottom line sits on CAP_Y
    y0 = CAP_Y - (len(lines)-1)*8.0
    return stack(cx, y0, lines, 8.0, size=F_CAP, fam=SANS, fill=SUB, anchor="middle")
def sym(cx, s):
    return T(cx, SYM_Y, s, size=F_SYM, fam=MATH, fill=INK, anchor="middle", style="italic")
def arrow(x0, x1):
    return line(x0, cy, x1, cy, stroke=ARROW, w=0.6, marker="arrowGrey")

# ---- lay the flow out left-to-right, then centre it in [M, W-M] -----
MW   = 5*4.2 + 4*1.0         # 24.8  square heatmap
ZW   = 2*4.2 + 1*1.0         # 9.4   representation strip
OPG  = 9                     # matrix edge <-> operator centre
AGAP = 4                     # element edge <-> arrow tip
AL   = 28                    # arrow line length
STEP = 2*AGAP + AL           # advance consumed by one arrow
FBOX = 22                    # model box
NBW, NBH = 46, 22            # I(Z;Y) node
PW, PH   = 44, 40            # sigmoid panel (deliberately compact)

xX  = 0.0
xE  = xX + MW + 2*OPG
xXt = xE + MW + 2*OPG
xF  = xXt + MW + STEP
xZ  = xF + FBOX + STEP
xN  = xZ + ZW + STEP
xP  = xN + NBW + STEP
SH  = M + (W - 2*M - (xP + PW)) / 2                 # centring shift
xX, xE, xXt, xF, xZ, xN, xP = (v + SH for v in (xX, xE, xXt, xF, xZ, xN, xP))

# X  +  eps  =  X-tilde
g,  mw,  _ = heat(xX,  cy-MW/2, 5, 5, "clean", 11)
g2, mw2, _ = heat(xE,  cy-MW/2, 5, 5, "noise", 42)
g3, mw3, _ = heat(xXt, cy-MW/2, 5, 5, "noisy", 7)
add(g,  cap(xX +mw /2, ["input",   "data"]),    sym(xX +mw /2, "X"))
add(g2, cap(xE +mw2/2, ["noising", "process"]), sym(xE +mw2/2, "\u03B5"))
add(g3, cap(xXt+mw3/2, ["noised",  "data"]),    sym(xXt+mw3/2, "X\u0303"))
add(T(xX+MW+OPG, cy+3.5, "+", size=F_SYM, fam=MATH, fill=SUB, anchor="middle"))
add(T(xE+MW+OPG, cy+3,   "=", size=F_SYM, fam=MATH, fill=SUB, anchor="middle"))
add(T(xXt+mw3/2, SYM_Y+9, "(SNR \u03B7)", size=F_SUB, fam=MATH, fill=SUB,
      anchor="middle"))

# -> f (fit model)
add(arrow(xXt+MW+AGAP, xF-AGAP))
add(rrect(xF, cy-FBOX/2, FBOX, FBOX, rx=4, fill="#fff", stroke=INK, sw=0.7),
    T(xF+FBOX/2, cy+4, "f", size=F_SYM+1, fam=MATH, style="italic", anchor="middle"),
    cap(xF+FBOX/2, ["fit", "model"]))
# -> Z (representation)
add(arrow(xF+FBOX+AGAP, xZ-AGAP))
gz, zw, _ = heat(xZ, cy-15.1, 6, 2, "rep", 3)
add(gz, cap(xZ+zw/2, "representation"), sym(xZ+zw/2, "Z"))
# -> I(Z;Y) node, captioned "quantify representation quality"
add(arrow(xZ+ZW+AGAP, xN-AGAP))
add(rrect(xN, cy-NBH/2, NBW, NBH, rx=4, fill=HAIR2, stroke=INK, sw=0.7),
    T(xN+NBW/2, cy+3.6, "I(Z\u2009;\u2009Y)", size=F_MATH, fam=MATH,
      style="italic", anchor="middle"))
node_cx = xN + NBW/2
add(stack(node_cx, CAP_Y-16, ["quantify", "representation", "quality"], 8.0,
          size=F_SUB, fam=SANS, fill=SUB, anchor="middle"))
# -> sigmoid plot (logistic I(Z;Y) vs SNR eta)
add(arrow(xN+NBW+AGAP, xP-AGAP))
py = cy - PH/2
add(rrect(xP, py, PW, PH, rx=3, fill="#fff", stroke=HAIR, sw=0.5))
ox, oy   = xP+12, py+PH-11
axw, axh = PW-16, PH-19
add(line(ox, oy, ox+axw, oy, stroke=INK, w=0.5))
add(line(ox, oy, ox, oy-axh, stroke=INK, w=0.5))
k, x0 = 10.0, 0.5
s0, s1 = 1/(1+math.exp(k*x0)), 1/(1+math.exp(-k*(1-x0)))
pts = []
for i in range(61):
    t = i/60
    v = (1/(1+math.exp(-k*(t-x0))) - s0) / (s1 - s0)
    pts.append(f"{ox+t*axw:.2f},{oy-v*(axh-3):.2f}")
add(path("M" + " L".join(pts), stroke=ACCENT, sw=1.2))
add(T(ox+axw/2, py+PH-3, "SNR \u03B7", size=F_AXIS, fam=MATH, fill=SUB,
      anchor="middle"))
add(f'<text x="{xP+6:.2f}" y="{oy-axh/2:.2f}" font-family="{MATH}" font-size="{F_AXIS}" '
    f'font-style="italic" fill="{SUB}" text-anchor="middle" '
    f'transform="rotate(-90 {xP+6:.2f} {oy-axh/2:.2f})">I(Z;Y)</text>')

# ---- auxiliary-signal Y box (compact; icon on the left of each cell) -
ICON_DY = {"spatial": 0.0, "clone": 3.9, "cite": 2.0, "time": -0.9}
YBOX_BG, YBOX_DIV = "#F5F5F5", "#CFCFCF"     # neutral grey, no blue tint
ptop, ph = 96, 48
add(rrect(M, ptop, W-2*M, ph, rx=0, fill=YBOX_BG, stroke=INK, sw=0.8))
# Y connector: node -> box
add(line(node_cx, ptop, node_cx, cy+NBH/2, stroke=ACCENT, w=0.8, marker="arrowTeal"))
add(T(node_cx+3.5, (ptop + cy+NBH/2)/2 + 2.5, "Y", size=F_SYM, fam=MATH,
      fill=ACCENT, style="italic"))
# header  ("auxiliary signal Y")
hx = M + 8
add(T(hx, ptop+14, "auxiliary signal", size=F_HEAD, fam=SANS, fill=INK, weight="bold"))
add(T(hx + text_width("auxiliary signal", F_HEAD, SANS, "bold") + 3.5, ptop+14,
      "Y", size=F_HEAD+1, fam=MATH, fill=INK, style="italic"))
# four cells: icon left, name + assay right — packed and centred as a group
cmid = ptop + 32
IW, IGAP, GAPB = 22, 8, 14             # icon budget, icon->text gap, block gap
blocks = []
for ap in AUX_PANELS:
    tw = max(text_width(ap["title"], F_TITLE, SANS, "bold"),
             text_width(ap["assay"], F_SUB, SANS, style="italic"))
    blocks.append((ap, IW + IGAP + tw))
total = sum(bw for _, bw in blocks) + GAPB*(len(blocks)-1)
bx = M + ((W - 2*M) - total)/2        # centre the packed row
for i, (ap, bw) in enumerate(blocks):
    if i > 0:
        add(line(bx-GAPB/2, ptop+22, bx-GAPB/2, ptop+ph-5, stroke=YBOX_DIV, w=0.5))
    icx = bx + IW/2
    add(group_scale(ICON[ap["kind"]](icx, cmid + ICON_DY[ap["kind"]]),
                    icx, cmid, 0.78))
    tx = bx + IW + IGAP
    add(T(tx, cmid-1, ap["title"], size=F_TITLE, fam=SANS, weight="bold", fill=INK))
    add(T(tx, cmid+9.5, ap["assay"], size=F_SUB, fam=SANS, fill=SUB, style="italic"))
    bx += bw + GAPB

# =====================================================================
# PANEL b  --  booktabs table (horizontal rules only)
# =====================================================================
# columns: key -> (x, w, header_lines, align)
COLS = [
    ("mod",  15,  60, ["Data", "modality"],        "start"),
    ("tag",  75,  55, ["Tag"],                     "start"),
    ("aux",  130, 86, ["Auxiliary", "signal"],     "start"),
    ("n",    216, 46, ["N samples"],               "start"),
    ("umis", 262, 48, ["Mean", "UMI / cell"],      "start"),
    ("mdl",  310, 72, ["Model", "families"],        "start"),
    ("noi",  382, 71, ["Noising", "process"],       "start"),
]
col = {c[0]: c[1:] for c in COLS}   # key -> (x, w, header_lines, align)
LEFT, RIGHT = 15, W-M          # 15 .. 453
PAD = 4
DYT = 9.5                       # line spacing in table cells

yT = ptop + ph + 24
add(T(M, yT-9, "b", size=F_PANEL, weight="bold"))

head_h = 25                     # room for up to 2 header lines (rule clears descenders)
add(line(LEFT, yT, RIGHT, yT, stroke=INK, w=0.8))
for key, cx, w, head, align in COLS:
    if key == "n":
        # italic math N + bold-sans "samples"
        add(T(cx+PAD, yT+10.5, "N", size=F_HEAD+0.5, fam=MATH, fill=INK, style="italic"))
        nx = cx+PAD + text_width("N", F_HEAD+0.5, MATH, style="italic") + 2
        add(T(nx, yT+10.5, "samples", size=F_HEAD, fam=SANS, fill=INK, weight="bold"))
        continue
    for li, ln in enumerate(head):
        add(T(cx+PAD, yT+10.5+li*9.5, ln, size=F_HEAD, fam=SANS, fill=INK,
              weight="bold", anchor=align, max_w=w-2*PAD))
add(line(LEFT, yT+head_h, RIGHT, yT+head_h, stroke=INK, w=0.5))

def merged(cx, w, lines, gmid, size, font=SANS, dy=9.5):
    y0 = gmid + 2.8 - (len(lines)-1)*dy/2
    return stack(cx+PAD, y0, lines, dy, size=size, fam=font, fill=INK,
                 max_w=w-2*PAD)

row_h = 27
y = yT + head_h
for gi, grp in enumerate(GROUPS):
    gtop = y
    for ri, row in enumerate(grp["rows"]):
        ctr = y + row_h/2
        # tag (plain typewriter text, left-aligned under "Tag")
        add(T(col["tag"][0]+PAD, ctr+2.8, row["tag"], size=F_TAG, fam=TT, fill=INK))
        # auxiliary signal (multi-line, vertically centred)
        al = row["aux"]
        ay0 = ctr + 2.8 - (len(al)-1)*DYT/2
        add(stack(col["aux"][0]+PAD, ay0, al, DYT, size=F_BODY, fam=SANS,
                  fill=INK, max_w=col["aux"][1]-2*PAD))
        # N samples
        if row["n"] is None:
            add(blank(col["n"][0]+PAD, ctr+1, w=col["n"][1]-2*PAD-6))
        else:
            add(T(col["n"][0]+PAD, ctr+2.8, f'{row["n"]:,}', size=F_BODY, max_w=col["n"][1]-2*PAD))
        # mean UMI / cell
        u = row["umis"]
        if u == "na":
            add(T(col["umis"][0]+PAD, ctr+2.8, "\u2014", size=F_BODY, fill=FAINT))
        elif u is None:
            add(blank(col["umis"][0]+PAD, ctr+1, w=col["umis"][1]-2*PAD-6))
        else:
            us = f'{u:,}' if isinstance(u, (int, float)) else str(u)
            add(T(col["umis"][0]+PAD, ctr+2.8, us, size=F_BODY, max_w=col["umis"][1]-2*PAD))
        # light within-group rule: only across per-row columns (tag..mdl),
        # never crossing the merged modality / model / noising cells
        if ri < len(grp["rows"])-1:
            add(line(col["tag"][0], y+row_h, col["mdl"][0], y+row_h, stroke=HAIR2, w=0.5))
        y += row_h
    gmid = (gtop + y)/2
    add(merged(col["mod"][0], col["mod"][1], grp["modality"], gmid, F_MOD))
    add(merged(col["mdl"][0], col["mdl"][1], grp["models"], gmid, F_MODEL, dy=9.5))
    add(merged(col["noi"][0], col["noi"][1], grp["noise"], gmid, F_NOI))
    if gi < len(GROUPS)-1:
        add(line(LEFT, y, RIGHT, y, stroke=HAIR, w=0.5))

add(line(LEFT, y, RIGHT, y, stroke=INK, w=0.8))     # bottom rule
H = y + 14

# =====================================================================
svg = (f'<svg xmlns="http://www.w3.org/2000/svg" '
       f'width="6.5in" height="{H/IN:.4f}in" viewBox="0 0 {W:.2f} {H:.2f}" '
       f'font-family="{SANS}">'
       f'<rect x="0" y="0" width="{W:.2f}" height="{H:.2f}" fill="#ffffff"/>'
       + DEFS + "".join(S) + "</svg>")

with open(OUT_SVG, "w", encoding="utf-8") as f:
    f.write(svg)
print(f"wrote {OUT_SVG}   {W:.0f} x {H:.0f} pt   =   6.50 x {H/IN:.2f} in")

# ---- also emit a vector PDF (optional; needs playwright + chromium) --
# Rendered through Chromium so the embedded Computer Modern faces are used
# and all geometry stays vector.  Skipped cleanly if playwright is absent.
OUT_PDF = OUT_SVG[:-4] + ".pdf" if OUT_SVG.endswith(".svg") else OUT_SVG + ".pdf"
try:
    from playwright.sync_api import sync_playwright
    _html = ("<!doctype html><meta charset='utf-8'>"
             "<style>*{margin:0;padding:0}svg{display:block}</style>" + svg)
    with sync_playwright() as _p:
        _b = _p.chromium.launch()
        _pg = _b.new_page()
        _pg.set_content(_html, wait_until="networkidle")
        _pg.pdf(path=OUT_PDF, width="6.5in", height=f"{H/IN:.4f}in",
                print_background=True,
                margin={"top": "0", "bottom": "0", "left": "0", "right": "0"})
        _b.close()
    print(f"wrote {OUT_PDF}")
except Exception as _e:
    print(f"(PDF export skipped: {_e})")